apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    autoscaling.knative.dev/target: "10"
  name: llama3-8b
spec:
  predictor:
    minReplicas: 1
    model:
      modelFormat:
        name: nvidia-nim-llama3-8b-instruct
      resources:
        limits:
          cpu: 12
          memory: 32Gi
          nvidia.com/gpu: 1
        requests:
          cpu: 6
          memory: 16Gi
          nvidia.com/gpu: 1
      runtime: nvidia-nim-llama3-8b-instruct-1.0.3
      storageUri: pvc://models-pvc/
