apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-repository
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: gl4f-filesystem