{{- if .Values.clusterAccess.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pod-manager.fullname" . }}-cluster-role-binding
  {{- if .Values.clusterAccess.clusterRoleBinding.name }}
  name: {{ .Values.clusterAccess.clusterRoleBinding.name }}
  {{- end }}
  labels:
    {{- include "pod-manager.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "pod-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "pod-manager.fullname" . }}-cluster-role
  {{- if .Values.clusterAccess.clusterRole.name }}
  name: {{ .Values.clusterAccess.clusterRole.name }}
  {{- end }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}